# west.yml (at the root of your app repo)
manifest:
  version: "0.13"

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0        # <-- pin the Zephyr version/tag/sha you want
      import:
        path-prefix: deps     # optional: place imported projects under deps/
        name-allowlist:
          - modules
          - tools
          - hal
          - bootloader
          - cmsis
    - name: hal_espressif
      remote: zephyrproject-rtos
      revision: main
      path: modules/hal/espressif

  self:
    path: app                 # how your app will appear inside the workspace

